name: Robô ETL Anbima

# Quando ele roda?
on:
  schedule:
    # Roda às 10:00 UTC (que é 07:00 da manhã no Brasil) de Segunda a Sexta
    - cron: '0 10 * * 1-5'
  workflow_dispatch:      # Permite rodar manualmente clicando no botão

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Dá permissão para o robô escrever no seu repositório (salvar o banco)
    permissions:
      contents: write
      
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        # AQUI ESTÁ A CORREÇÃO: Adicionei 'scipy' e 'lxml' que faltavam
        run: |
          pip install pandas requests lxml openpyxl numpy scipy

      - name: RODAR O ETL
        run: python etl_anbima.py

      - name: Salvar novo Banco de Dados
        run: |
          git config --global user.name 'Robo Claudio Paes'
          git config --global user.email 'robo@claudiopaes.com.br'
          git add meu_app.db
          # O "|| echo" serve para não dar erro se não tiver dados novos no dia
          git commit -m "Atualização automática dos dados" || echo "Sem mudanças para commitar"
          git push
